### ISSUE TITLE
Allow multiple commands against targets

### ISSUE THREAD

**Issue by arj22** [canonical/nrpe_exporter#2]
Hello,

Is it possible to specify multiple commands against targets?

I have tried the following and it seems to fail. It would be easy to group all checks for targets in a job.
```
- job_name: 'nrpe'
    metrics_path: /export
    params:
      target: ['127.0.0.1:5666']
      command: ['check_load','check_users']
    static_configs:
      - targets:
        - 127.0.0.1:9275
```

Thanks.

**Comment by brian-brazil** [comment]
You can create a job per check.

**Comment by yadavpravinb** [comment]
@brian-brazil,@arj22 , Can you please give the format of how multiple commands will write in prometheus.yml file???
I didn't find the proper specific answer on the internet.  I stuck on this point for the last 2 days.
thanks in advance!!

**Comment by simonaronsson** [comment]
> @brian-brazil,@arj22 , Can you please give the format of how multiple commands will write in prometheus.yml file??? I didn't find the proper specific answer on the internet. I stuck on this point for the last 2 days. thanks in advance!!

```yaml
scrape_configs:
  - job_name: nrpe_check_load
    metrics_path: /export
    params:
      command: [check_load]
    static_configs:
      - targets: 
        - 'example.com:5666'
  - job_name: nrpe_check_users
    metrics_path: /export
    params:
      command: [check_users]
    static_configs:
      - targets: 
        - 'example.com:5666'
```

 as advised by Brian.
